2024-08-08 04:33:35.754144
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Elsiros_result\controllers\Robofest_TEAM\main_pb.py", line 118, in main_procedure
    robot = CommunicationManager(1, '127.0.0.1', int(Port), logarg, team_color=sys.argv[3].upper(), player_number = int(sys.argv[4]), time_step = 25)
  File "C:\Elsiros_result\controllers\player\communication_manager_robokit.py", line 14, in __init__
    self.__client.connect_client()
  File "C:\Elsiros_result\controllers\player\robot_client.py", line 69, in connect_client
    welcome_message = self.socket.recv(8)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
