--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
  File "C:\Elsiros_result\controllers\Robofest_TEAM\main_pb.py", line 162, in write
    self.out.WriteText(string)
wx._core.wxAssertionError: C++ assertion "m_count == -1 || m_count == -2" failed at ..\..\src\msw\textctrl.cpp(284) in UpdatesCountFilter::UpdatesCountFilter(): wrong initial m_updatesCount value
Call stack:
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python39\lib\threading.py", line 908, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Elsiros_result\controllers\player\communication_manager_robokit.py", line 269, in run
    self.__update_history(message)
  File "C:\Elsiros_result\controllers\player\communication_manager_robokit.py", line 66, in __update_history
    self.logger.warning(f"WARNING! Large protobuf time rx delta = {delta}")
Message: 'WARNING! Large protobuf time rx delta = 19605'
Arguments: ()
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
