2024-08-08 04:33:35.722225
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Elsiros_result\controllers\player\communication_manager_robokit.py", line 267, in run
    messages_list = self.__client.receive2()
  File "C:\Elsiros_result\controllers\player\robot_client.py", line 128, in receive2
    chunk = self.socket.recv(1024)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
