2024-08-02 18:56:31.850512
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Downloads\GitHub\elsiros\Elsiros\controllers\player\communication_manager_robokit.py", line 250, in run
    messages_list = self.__client.receive2()
  File "C:\Users\User\Downloads\GitHub\elsiros\Elsiros\controllers\player\robot_client.py", line 128, in receive2
    chunk = self.socket.recv(1024)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
